### ISSUE TITLE
`defines.js` disappeared from `client/js/_author`

### ISSUE THREAD

**Issue by cjshawMIT** [atomicjolt/open_assessments#127]
various files depend on `client/js/_author/defines.js`, like `_edit_assessment` and `_new_assessment`, but that file has disappeared from the repo. It is present in this commit: 

```
https://github.com/atomicjolt/open_assessments/tree/84e2f6741b6c5d3e618e11c33aab7319d573a174/client/js/_author
```

This breaks builds. Can you put it back, please?

**Comment by BenHSmith13** [comment]
No, but I can finish ripping it out.

https://github.com/atomicjolt/open_assessments/pull/128

**Comment by cjshawMIT** [comment]
Ah, that would be good, too 👍 Thanks!
