### ISSUE TITLE
Movable Words Sandbox question doesn't consistently save Audio recording

### ISSUE THREAD

**Issue by resource11** [atomicjolt/open_assessments#419]
The order of when the user records audio versus adding movable words into the sequence region affects what is sent back to qbank, according to what I see in the state tree looking at the `Assessment` component using **React DevTools** in Chrome.

Using this assessment setting in the `_head.html` layout partial:
```
api_url      : "https://qbank-clix-staging.mit.edu/api/v1",
    bank:          "assessment.Bank%3A586eac6ced849b30a4ecc5d9%40ODL.MIT.EDU",
    assessment_offered_id: "assessment.AssessmentOffered%3A58c6d67eed849b1a873454ab%40ODL.MIT.EDU",
```
If the user records audio as the first step, then selects words for the movable words sequence, all the information (audio blob and word choice ids) gets stored in the `response` object and the `questionResults` object upon answer submission.

Yet, if the user selects word(s) first **then** records audio, the user gets this error in the console:

```
Uncaught TypeError: answer.get is not a function
    at eval (assessment_progress.js:77)
    at eval (immutable.js:4494)
    at List.__iterate (immutable.js:2208)
    at List.findEntry (immutable.js:4493)
    at List.findIndex (immutable.js:4734)
    at _default (assessment_progress.js:72)
    at combination (combineReducers.js:132)
    at computeNextEntry (instrument.js:138)
    at recomputeStates (instrument.js:172)
    at eval (instrument.js:550)
```

When saving the question, the word choice ids are stored in `questionResults`, but **the audio blob doesn't get stored*** in the state tree.

**Comment by dspencer001** [comment]
This should have been fixed by https://github.com/atomicjolt/open_assessments/pull/390

I cannot replicate it on master.

**Comment by resource11** [comment]
Ahh. I was testing on a local copy of your repo at {#387](https://github.com/atomicjolt/open_assessments/pull/387)... tested the most recent. All fixed. Thanks for that tweak!
