### ISSUE TITLE
Communicator breaks player assessment

### ISSUE THREAD

**Issue by cjshawMIT** [atomicjolt/open_assessments#433]
@jbasdf with your restore of the communicator, I now get this error on loading any assessment in the player.

![captura de pantalla 2017-05-11 a las 4 29 44 pm](https://cloud.githubusercontent.com/assets/4930129/25970566/1881cbaa-3667-11e7-99d4-d19fbb686476.png)

I think it's breaking on this line:

https://github.com/atomicjolt/open_assessments/blob/master/client/js/_player/components/main/assessment.jsx#L148

This happens on a clone of the AJ repo, not our fork. If I revert one commit to the previous, everything works fine.

**Comment by jbasdf** [comment]
I just uploaded a fix. The sendSize method was missing in the action.
